import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import { cookies } from "next/headers";

import Footer from "@/components/layout/Footer";
import Navigation from "@/components/layout/Navigation";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

import InitState from "./InitState";
import "./global.css";
import { GeistSans } from "geist/font/sans";

//* define fonts
export const playfair_Display = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair_Display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} ${playfair_Display.variable} relative selection:bg-slate-200/50`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <InitState>
            <div className="h-screen overflow-auto bg-black">
              <Navigation />
              {children}
              <Footer />
            </div>
          </InitState>
        </ThemeProvider>
      </body>
    </html>
  );
}
