import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navigation from "@/components/navigation/Navigation";

import "./global.css";
import { GeistSans } from "geist/font/sans";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <div className="h-screen overflow-auto bg-slate-200 selection:bg-slate-200">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
